### ISSUE TITLE
Shift clicking items

### ISSUE THREAD

**Issue by Megachin502** [Jessy1237/DwarfCraft#23]
shift clicking items when crafting causes them to disapear

**Comment by Jessy1237** [comment]
In what inventory? the players inventory, crafting table inventory or both?

**Comment by Jessy1237** [comment]
So i tested in both the crafting table inventory and the player inventory. The crafting mechanism is working as intended. You might want to look up what this plugin actually does as yes you do lose crafted materials at lower levels as you have a higher gain at higher levels.

**Comment by Megachin502** [comment]
Try making sticks in player inventory. Now hold shift and take the sticks out.

**Comment by Megachin502** [comment]
If you dont hold shift, and drag sticks out the plugin works intended, but holding shift makes all sticks completely disapear. Ex if It shows i can make 30 sticks with shift then i take it out, they will dissapear.

**Comment by Jessy1237** [comment]
I'm fairly sure I tried all cases but I'll try again when I'm home

**Comment by Megachin502** [comment]
If you still cant replicate it, I will make a youtube video for you

**Comment by Jessy1237** [comment]
Well it works for me, i can't seem to replicate this issue. I've tried several types of planks and it still doesn't replicate the issue.

**Comment by Jessy1237** [comment]
Run the dwarfcraft command, "/si 32" on your server and tell me the returns for the player that is losing all their mats

**Comment by drekryan** [comment]
I tried to replicate this on my end and wasn't able to. I tried both the players inventory and a crafting table grid with various different types of planks. With a standard Dwarf with no leveling I took a stack of planks and put them in the formation for a stick (two stacks of 32 planks) and shift-clicked them out of the inventory. I got a pretty consistent stack and a half of sticks (or 96 sticks) from one stack of planks. 

<img width="576" alt="screen shot 2016-11-04 at 1 24 59 pm" src="https://cloud.githubusercontent.com/assets/1168966/20015573/59eb1fba-a292-11e6-8900-c693b5b3b020.png">

3 sticks per craft \* 32 crafts = 96 sticks

<img width="366" alt="screen shot 2016-11-04 at 1 27 46 pm" src="https://cloud.githubusercontent.com/assets/1168966/20015635/8c0a732e-a292-11e6-8493-2e215cd02adf.png">

<img width="359" alt="screen shot 2016-11-04 at 1 27 58 pm" src="https://cloud.githubusercontent.com/assets/1168966/20015639/90cc9996-a292-11e6-897b-a9bdf07cdf24.png">

**Comment by drekryan** [comment]
This is an area that might be worth looking into improving though. There are some newer Spigot events we might be able to take advantage of here. I wonder if we could affect the craft amount before the craft happens instead of trying to modify the inventory on the fly afterwards.

If I have extra time I'll mess around with it for fun on another branch.

As for the items disappearing I haven't seen it in my testing. A video showing it would help and maybe what other plugins you are using that may conflict with this.

Are you up to date on Spigot (/ver on the Server)?

**Comment by Megachin502** [comment]
Yesterday my players were reporting the bug, so I tried it and it waa bugged. Today I tried replicating it and I can't get it to do what I did yesterday. I will keep it updated when exactly it does happen.

**Comment by Megachin502** [comment]
Could not pass event InventoryClickEvent to DwarfCraft v3.1.4

org.bukkit.event.EventException

```
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]

at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]

at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]

at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]

at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1861) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]

at net.minecraft.server.v1_10_R1.PacketPlayInWindowClick.a(SourceFile:33) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]

at net.minecraft.server.v1_10_R1.PacketPlayInWindowClick.a(SourceFile:10) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]

at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]

at java.util.concurrent.Executors.call(Executors.java:511) [?:1.8.0_101]

at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101]

at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]

at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]

at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]

at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]

at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]

at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
```

Caused by: java.lang.NullPointerException

```
at com.Jessy1237.DwarfCraft.listeners.DCInventoryListener.onInventoryClickEvent(DCInventoryListener.java:371) ~[?:?]

at sun.reflect.GeneratedMethodAccessor157.invoke(Unknown Source) ~[?:?]

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]

at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]

at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.10.2.jar:git-Spigot-570526c-c1b529e]

... 15 more
```

**Comment by Jessy1237** [comment]
It appears in your case that for some reason spigot is returning a null inventory.

**Comment by Jessy1237** [comment]
Even when i clicked outside the inventory to get a null inventory and then click the sticks i still don't get this exception or lose all my sticks.

**Comment by Jessy1237** [comment]
I do get the error when i click in a brewing stand though however it still doesn't lose all the sticks when i then go to craft in the players inventory.

**Comment by Megachin502** [comment]
I honestly have no idea how I came about this error

**Comment by Jessy1237** [comment]
Well i have fixed all the brewing stands errors, i'll release an update and see if you still encounter this issue.

**Comment by Megachin502** [comment]
You can put my video on the spigot page to demonstrate how training works. https://youtu.be/5UJl1820gu4

**Comment by Megachin502** [comment]
A bug I noticed in my video, the part where I hand in 5 sand then left click shows 5/15 then when I handed in 15 it leveled. And I left clicked again and it now says 5/40. Should be 0/40.

**Comment by Jessy1237** [comment]
So u deposited 5 and then had 15 on you when you levelled it? If so it's meant to carry over.

**Comment by Megachin502** [comment]
I handed in 5, i need 15 more so i handed 15. Then i leveled and next requirement i needed 40 blocks but for some reason I had 5 already handed in

**Comment by Megachin502** [comment]
And as you can tell from the video I did not have any extra sand in my inventory

**Comment by drekryan** [comment]
**Edit:** So I looked at this briefly. %totalcost% is what is used to display the total amount for that level. That placeholder is not affected by how much you have already deposited. So if it states 20, you need a total of 20 for that level. So when %depositedamount% reaches this %totalamount% you have met the requirement for that item. So the way @Megachin502 has customized his messages file is correct.

I have also tested this on my server and it is definitely bugged. First level for Pickaxe Use wants 16 Cobblestone. I gave him 6. On left click he shows that I have given him 6 out of 16 (which is correct). I then gave him another 10 (the exact amount left he was asking for). He leveled me but after the level he showed that I had 6 out of 32 deposited. It shouldn't have carried over that deposit of 6.

@Jessy1237 I can look at it later if I have time and make a PR for it or if you get to it before me you can fix it. A bit on the busy side today so not sure. But yeah one of the higher priority bugs as it undermines the leveling system a bit. 

---

That is actually a bug. I did look at the video. The first level wanted 20 sand. He had handed in 5 sand. Then came back and gave an additional 15 sand to meet the total of 20 sand for the level. However the next level did carry over 5 when it shouldn't have. So level 2 was 5/40 but should have carried over nothing as the exact amount to level was provided. This should have been 0/40.

Unless he just has it displaying differently on his server. And it is trying to say 20 more and not a total of 20. And was actually looking to receive 25 sand for the first level. I would have to look at the placeholders we provide there to know for sure. But if that was the case the first time he clicked the trainer it would have showed as 0/25 so i actually think what i said first is what it is doing and is a bug.

**Comment by drekryan** [comment]
Unless he just has it displaying differently on his server. And it is trying to say 20 more and not a total of 20. And was actually looking to receive 25 sand for the first level. I would have to look at the placeholders we provide there to know for sure.

**Comment by drekryan** [comment]
Opened the item carryover issue as a separate bug report #24 so we can stay on topic on this issue.

Besides the brewing stand fixes that were already made, is the shift-clicking issue still happening? Because I haven't been able to reproduce it at all. 

@Jessy1237 Possibly close this issue for now and if it happens again the issue can be reopened.

**Comment by Megachin502** [comment]
I havent too
