### ISSUE TITLE
Item deposits sometimes carry over when training when they shouldn't

### ISSUE THREAD

**Issue by drekryan** [Jessy1237/DwarfCraft#24]
As mentioned in Issue #23 items sometimes carry over when training with a trainer when they shouldn't.

Try this example as a way to replicate the issue.

(Ensure you are level 0 in Pickaxe use for this test)
1. Create a trainer for Pickaxe Use (Skill ID: 1)
2. Have 6 Cobblestone in your inventory and right click the trainer to train
3. You should now have 6 out 16 Cobblestone when you left click the trainer
4. Have exactly 10 Cobblestone in your inventory now and right click the trainer to train.
5. This should now be the total of 16 Cobblestone required to level. However you will notice that it carried over 6 Cobblestone when it shouldn't have.

**Comment by Megachin502** [comment]
Works for all levels and all initial hand ins
