### ISSUE TITLE
Shutdown Issue

### ISSUE THREAD

**Issue by martyboy14** [Jessy1237/DwarfCraft#26]
Im running on a linux agent to host my server, and whenever i shut the server down dwarfcraft doesnt shut down properly. so my server cant be used anymore till i reset the entire agent.

do you have / know / come up with a fix to this issue?
It would sadden me if i couldnt use this plugin, a large part of my developing RPG server revolves around it. 

[log without dwarfcraft.gz](https://github.com/Jessy1237/DwarfCraft/files/1355648/log.without.dwarfcraft.gz)
[log with dwarfcraft.gz](https://github.com/Jessy1237/DwarfCraft/files/1355649/log.with.dwarfcraft.gz)
[log after dwarfcraft (first reboot).gz](https://github.com/Jessy1237/DwarfCraft/files/1355650/log.after.dwarfcraft.first.reboot.gz)

**Comment by drekryan** [comment]
I’ll be happy to take a look if you could take the time to put the logs on a site such as pastebin and share the link to that here since I am not able to view the console logs the way you have shared them.

**Comment by martyboy14** [comment]
allright, thanks for taking the time to.
here are the files reuploaded into pasted (pastebin was under heavy load too long)

log without dwarfcraft:  http://pasted.co/7e528df7
log with dwarfcraft:  http://pasted.co/daab69c0
log after dwarfcraft (first reboot):  http://pasted.co/96e442d1

logs confirm that dwarfcraft wont shut down, and keep the agent from closing down properly.

**Comment by Jessy1237** [comment]
Thats odd, all that dwarfcraft does on disable is remove the prefixes from every offlineplayer on the server so it shouldn't really hang or freezeup. How many player files do you have on your server, also i'm curious as to what that End of File exception is with your world, is your world corrupt?

**Comment by martyboy14** [comment]
okay issue lays within running a linux agent i believe. i tested on windows pc now. and it just worked properly. i will look further into the input / output error because i feel that creates the problems for dwarfcraft shutting down. much appreciated that you took the time to look into it anyways, but i think its not a plugin issue by now.
