### ISSUE TITLE
Error on disable

### ISSUE THREAD

**Issue by martyboy14** [Jessy1237/DwarfCraft#27]
Heya, 
I seem to get the following error when i disable my server: 
(this is the only reference to DwarfCraft in log)
https://pastebin.com/embed_js/JhchtKj7

is this an Error that can be ignored or might this cause problems later?
thanks in advance.

**Comment by Jessy1237** [comment]
This bug was supposedly caused because DwarfCraft was unable to find a permissions plugin through Vault and this in turn caused the plugin to disable itself and try to use something that wasn't initialised.

tl;dr Fixed in in the latest commit
