### ISSUE TITLE
Effect command issues

### ISSUE THREAD

**Issue by tylerking** [Jessy1237/DwarfCraft#3]
When using /effectinfo doitliketyler 6 instead of showing info about that skill it prints:

https://imgur.com/a/Uv3Ao

When using /effect doitliketyler 6 it clashes with UltimateCore and UC gives me a healing effect.

**Comment by drekryan** [comment]
Yeah /effect is actually a default Minecraft command. The help on this is incorrect and the command should be /effectinfo doitliketyler 131
