### ISSUE TITLE
A Couple Errors

### ISSUE THREAD

**Issue by tylerking** [Jessy1237/DwarfCraft#38]
Hey there. Glad to see you back working on this plugin. I swapped to the new version and I'm getting a couple errors. I was able to fix the first one by just updating the effects.csv but I don't know whats causing the second one and the plugin currently won't load. I'm running on PaperSpigot 1.12.2 and here are the errors:

https://pastebin.com/raw/KbfrjWsm

Thoughts?

**Comment by Jessy1237** [comment]
Have you reset all the config files as stated in the version changes?

**Comment by tylerking** [comment]
I did indeed. I wanted to start from scratch and check out the new GUI's before I did anything else.

**Comment by drekryan** [comment]
This was caused by our switch to Material names instead of numerical ids.. reset all configs except the DwarfCraft database file

**Comment by Jessy1237** [comment]
so this happens when you start the server?

**Comment by Jessy1237** [comment]
I just made a fresh server with only the plugin files and the spigot runnable and i don't seem to get this error on first boot up. Do you have all the dependencies like Vault, a perms plugin and Citizens?

**Comment by drekryan** [comment]
Would you be able to zip up your DwarfCraft config folder and link it here?

**Comment by tylerking** [comment]
I have all the dependencies and this happens on a fresh install. Here is the config folder:

http://www.doitliketyler.com/lacuna/DwarfCraft.zip

**Comment by Jessy1237** [comment]
With your configs it loads up fine on my fresh server. What other plugins are you currently running on your test server?

**Comment by tylerking** [comment]
https://pastebin.com/raw/UDayKubJ

**Comment by tylerking** [comment]
Startup Errors

https://pastebin.com/raw/J8kfxfp9

**Comment by Jessy1237** [comment]
I downloaded paperspigot as well and with a fresh install with your configs i don't get this issue either. Could it be LuckPerms thats causing the issue? What version of LuckPerms are you using?

**Comment by tylerking** [comment]
I tried removing LuckPerms but that didn't fix the issue. Not sure what else to check.

**Comment by Jessy1237** [comment]
Could you possibly zip up your whole plugins folder and your paperspigot runnable and post it here

**Comment by tylerking** [comment]
I could without the Premium plugins because I do not want to get banned from Spigot. It also looks like SnUncle is getting the same error as me and he has fewer plugins than I do.

**Comment by Jessy1237** [comment]
Don't worry about it. I've used PermissionsEX and I do not get this issue, however when i used LuckPerms i do seem to get this issue. So i'll do some investigating with LuckPerms and see if i can resolve this issue.

**Comment by tylerking** [comment]
Ok. I’ll hold tight until you figure out what’s going on with LP and DC.

**Comment by Jessy1237** [comment]
Fixed this in the latest commit even though it didn't want to show it. I'll be uploading it to spigot shortly

**Comment by tylerking** [comment]
Perfect. Thanks for taking care of that so fast. Cheers

**Comment by drekryan** [comment]
@doitliketyler please keep us updated here on GitHub.. It will most likely be a pretty active next couple months of DwarfCraft development with adding new features and making changes. The GUI update is the start of that but Jessy1237 and I have a few other cool ideas which may make their way into the plugin.

**Comment by tylerking** [comment]
Definitely. I'm looking forward to it. Ciao
