### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by tylerking** [Jessy1237/DwarfCraft#4]
I went to create a Greeter and it seems the "greetermessages.config" file is missing. I can create the file manually but do you have an example of what its supposed to look like?

**Comment by drekryan** [comment]
The default file for this is located at https://github.com/Jessy1237/DwarfCraft/blob/master/src/default_files/greeters.config

Is it not generating if the file is not there? If so I can take a look into why that may be happening

The file should be called greeters.config

**Comment by tylerking** [comment]
Ah ok. I was looking for "greetermessages.config" because it prints this:

https://imgur.com/a/5zXkH

**Comment by drekryan** [comment]
Yeah it seems that a lot of the the help messages are outdated and well not very helpful. Ill go through and try to update them.
