### ISSUE TITLE
Alphabetize Listtrainers

### ISSUE THREAD

**Issue by tylerking** [Jessy1237/DwarfCraft#42]
Hey there. Got a request this time. Would it be possible to alphabetize the trainers in the GUI so its easier to find the one you are looking for?

**Comment by drekryan** [comment]
I like the idea of sorting the list, but it may make more sense to possibly sort by Skill ID (ex. Pickaxe Use with Skill ID 1) would be first. I’ll talk to @Jessy1237 about the best way to sort the list.

Either way it’s something we can do easily.

**Comment by drekryan** [comment]
Its very offtopic but had to share my little project :p 

Thought you may like it :)
https://www.youtube.com/watch?v=6M3t6dhtc4o&feature=youtu.be

**Comment by tylerking** [comment]
Ooooh...yes that's very nice. I'll be looking forward to that. Thanks for sharing.

**Comment by tylerking** [comment]
You guys are awesome. Thank you.

**Comment by Jessy1237** [comment]
Well i wont release it to spigot until @drekryan finished his brain egg. If you know how to compile with maven then go ahead and build a snapshot build off the source.
