### ISSUE TITLE
Book Title

### ISSUE THREAD

**Issue by tylerking** [Jessy1237/DwarfCraft#65]
Don't see a way to change the "Dwarfcraft Pocket Guide" title. Could you add this?

**Comment by drekryan** [comment]
It’s hardcoded at the moment.. possibly..

**Comment by drekryan** [comment]
what were you trying to change the book title to? curious

**Comment by tylerking** [comment]
"Races of Pathfinder" because that server Dwarfcraft is on is called Pathfinder

**Comment by Jessy1237** [comment]
I don't think we will support changing the title of the book as its only meant to suffice as a tutorial for DwarfCraft. I'd recommend using the essentials written book feature if you want to make books related specifically to your server, how it works and its rules etc.
