### ISSUE TITLE
Reload Command Error

### ISSUE THREAD

**Issue by tylerking** [Jessy1237/DwarfCraft#67]
Using the reload command sends an internal error message and spits this out in the console:

https://pastebin.com/raw/1eM9AG0m

**Comment by Jessy1237** [comment]
I can't seem to replicate this reload issue. Did you reset the following configs on update. DwarfCraft.config, messages.config, effects.csv, skills.csv and races.config.

**Comment by tylerking** [comment]
I reset everything but the races.config. It didn't mention that I needed to.

**Comment by Jessy1237** [comment]
i'll add a mention of it to the updates as we added new Material Icons for the Races GUI

**Comment by Jessy1237** [comment]
Do you still get the issue after resetting the races.config?

**Comment by tylerking** [comment]
Yep: https://pastebin.com/raw/LudncC1b

**Comment by drekryan** [comment]
Please zip and post your current config files if possible.. the error there isn’t giving us much to see what may be happening

**Comment by tylerking** [comment]
This is happening on a fresh install.

**Comment by Jessy1237** [comment]
what plugins are you running and what version of PaperSpigot.

**Comment by tylerking** [comment]
Paper version git-Paper-1329 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
https://pastebin.com/raw/UJt4fFXF

**Comment by Jessy1237** [comment]
I think i found the issue. Try the 4.1.1 release. Is it fixed?

**Comment by tylerking** [comment]
Reload command is good to go now. Thanks for the quick fix.
