### ISSUE TITLE
Race GUI - Specialised Skills

### ISSUE THREAD

**Issue by tylerking** [Jessy1237/DwarfCraft#68]
I really like this new GUI you have however the Specialised Skills should display the skill name and not the id. Those IDs will mean absolutely nothing to a player. Will you change this?

Also, you are using "Specialised" on this one GUI and specialize/specialized throughout the rest which is the more common spelling of the word. Will you adjust that spelling?

**Comment by drekryan** [comment]
This is something that was considered during the development of the GUI because we fully agree but it would possibly be very verbose if we displayed the skill named in full. The tooltip could take half the screen. We will have to consider alternatives here

**Comment by tylerking** [comment]
No way to just put 2 skills per line maybe?

**Comment by Jessy1237** [comment]
well each race specialises in about 10-20 skills and the char limit per line in the lore is about 30. So it will only fit 2 skills per line probably. This will add 5-10 more lines to the lore which on small screens is quite a lot. I am thinking of changing it, however it is still possible to use skill ids in all the dwarfcraft commands.
