### ISSUE TITLE
Race Commands

### ISSUE THREAD

**Issue by tylerking** [Jessy1237/DwarfCraft#69]
These were not obsolete for me and I used them heavily. Please put them back. Also, why are you now capping races at 9? Seems like you are stripping out features without considering how your current supporters use Dwarfcraft.

**Comment by Jessy1237** [comment]
What race command are you talking about as the admin aspect of the race command is still there and usable. Also it was capped at 9 as logistically it had to be capped somewhere and 9 seemed like a nice number as it filled out the inventory nicely as they are 9 wide. Personally I recommend the use of 4 races as splitting up the specialisation into any more (as of now as there aren't many recent skills and they are split up into 4 distinct categories) makes the races a bit bare. If not 9 what number would you recommend capping the races at for the GUI as the only next number would be 18 and that seems a bit far fetched.

**Comment by drekryan** [comment]
As a contributor to DwarfCraft I’ll leave my comment to the second part of the question. We are currently removing less used features and trying to replace them with better alternatives that will get more use. With almost every feature removed in 4.1 we listed an alternative which would be far better supported than we would have supported it. Need greeters, use Citizens. They have far better support for that. Need aliases, use the one provided by Bukkit/Spigot/PaperSpigot. It does all the same things and more. We aren’t removing features for the sake of removing features. As for why we placed a cap on the races, I think Jessy explained that one pretty well. Inventories in Minecraft are in fixed multiples of 9. Ex: 9, 18, 24, etc. When making the Race GUI we opted not to support paging on the GUI. We felt having a limited number of races helps the player feel less overwhelmed when selecting a race. The cap isn’t there for an sort of performance reason or to remove customization. I may consider auto expanding the GUI based on the number of races loaded. ex. If you add 8 you get one row, 11 races would add the second row, etc up until the 6 row cap.. which would make 54 races (however I think we reserve the bottom row of the GUI so it could possibly be increased to 45). But still from a design perspective we agreed that if you opened a GUI on server join to pick a race and were presented with 45 races you would feel very very overwhelmed and most likely wouldn’t make a clear choice. I’m not against raising the cap to the 45 using the method I just described but unless we add paging to it (which would be overkill) we had to add a cap somewhere and 9 felt like a reasonable amount of races to choose from.

**Comment by tylerking** [comment]
Capping at 9 is strict with a system that lets you create your own skills which I plan to do and I want some wiggle room with my races. I already have 9 but what if I decide to add 5 more? I would feel much more comfortable with a cap at 18. Also, the command that lets a player change their own race is gone which I was using in many different scenarios and really need it to come back.

**Comment by drekryan** [comment]
I’ll bump the cap of 9 races. However I think I am still misunderstanding what is missing from the race command. Players should run /dc race and select their new race. Admins still have the ability through /dc race to set another players race.

**Comment by tylerking** [comment]
Well, that's assuming we want to use the GUI and currently I don't. Its nice but doesn't fit how my players set up their character in a tutorial I already created specifically with those commands. Plus I am listening for those specific command events through Denizens to do things.

**Comment by drekryan** [comment]
I understand now.. I’ll make some changes to address these concerns

**Comment by Jessy1237** [comment]
The command events still take place even with the gui. If you're talking about the race change event that dwarfcraft fires.

**Comment by tylerking** [comment]
It doesn't from my side. I tried using it before I posted this and it does not change the race.

**Comment by Jessy1237** [comment]
The DwarfRaceChangeEvent doesn't fire when a player changes their race?

**Comment by tylerking** [comment]
I'm saying the commands don't work on DwarfCraft side and the race isn't changed with them. I don't' want to use the GUI...I want to use the commands.
