### ISSUE TITLE
command the same as..

### ISSUE THREAD

**Issue by downboy** [Jessy1237/DwarfCraft#7]
Hallo,

the command alias:  **ss** is also used for silkspawners can you plz fix it so that we can use you plugin and silkspawners.

**Comment by drekryan** [comment]
How would you suggest fixing it? There really isn't much control over command collisions. You could try using /skills or /skillsheet to avoid the collision or if you know how remap the commands in the commands.yml file of your server.

**Comment by Jessy1237** [comment]
Theres nothing i can really do except for remove the alias however that defeats the purpose of having the alias. As drek said you can fix it by editting the commands.yml or the plugin.yml inside the plugins.
