### ISSUE TITLE
Trainer GUI Reload Bug

### ISSUE THREAD

**Issue by tylerking** [Jessy1237/DwarfCraft#71]
On a fresh install if I join and use /dc reload without doing anything that old trainer bug comes back where it doesn't show all the trainers.

**Comment by Jessy1237** [comment]
I tried with the 4.1.2 build on spigot, tp'd 1000 blocks away, did /dc reload and then tried the /dc list and I had all the trainers in the list. Even tried restarting the server while 1000 blocks away and tried the two commands and still couldn't replicate this issue.

**Comment by tylerking** [comment]
Well, this happens to me on a fresh install and I have trainers that are more than 1000 blocks away.

https://imgur.com/a/KjjDd

**Comment by Jessy1237** [comment]
can i come test it on your server?

**Comment by tylerking** [comment]
Any luck with this one?

**Comment by drekryan** [comment]
Not yet. It’s going to require more testing and debugging unfortunately as we have not been able to reproduce the issue yet on our end.

When we figure out what is causing the issue we will be able to make a correction. Both me and Jessy haven’t had the time yet this past week to put a lot of time into further looking into it. Hope to find the time to take another look soon. I’ve been sick with the cold so I haven’t touched DwarfCraft in about a week personally.

**Comment by tylerking** [comment]
No worries. It's not crucial...I was just curious. Thanks for the update tho.

**Comment by tylerking** [comment]
And...I hope you start feeling better.

**Comment by Jessy1237** [comment]
well i've tried what we discussed earlier on your server and this still doesn't replicate the issue. Could you possibly try to see if the issue persists with just the bare minimums to run DwarfCraft. i.e citizens, vault and perm plugin.

**Comment by drekryan** [comment]
I think we need to work on an Issue Template for DwarfCraft Issues to prevent issues without enough information. Its best to gather as much information as possible when the issue occurs so we can actually dig through the hundreds of lines of DwarfCraft code to reproduce and debug the issue. 

A generic/vague issue is like a needle in a haystack with the amount of code that DwarfCraft has and there usually isn't much we can do to correct the issue without proper steps to cause the issue, things you tried, things that don't cause the issue, what workarounds do you know for the issue, etc.

That being said this issue currently has insufficient information to investigate this issue and will be marked as "needs more information". If you hit this issue again in the future and would like to update the issue which further information, please reopen this issue at that time.

**Comment by tylerking** [comment]
I gave you guys enough information and you have even replicated the issue on your own before. I also told you directly that this happens with the bare minimums installed.
