### ISSUE TITLE
Unable Train at Level 0

### ISSUE THREAD

**Issue by tylerking** [Jessy1237/DwarfCraft#72]
So with the latest update, I can no longer train because all of the trainers say this:

https://imgur.com/a/T42Zn

As you can see I'm level 0. This happens with any trainer no matter what race I am. What would be causing this?

**Comment by drekryan** [comment]
Wat did you set the maximum level as when setting up the trainer? I believe max comes before min in the command for some unknown reason. Also are using 0 or -1 as the minimum level?

**Comment by tylerking** [comment]
The max is at 30, default. I didn't fuss with the levels at all.

**Comment by tylerking** [comment]
Just to be sure I went ahead and did a fresh install with default settings and this is still happening.

**Comment by drekryan** [comment]
What I mean is when running the /dc create command the levels are backwards. What I suppose probably happened if you but the min level at 30 and the max level at 0. 

For Example:
/dc create 202 Meow 1 0 30 VILLAGER

will set the Max level at 0 preventing you from trainer and well min level at 30 which would also cause a different problem. The trainer should be created like so

 /dc create 202 Meow 1 30 0 VILLAGER

**Comment by Jessy1237** [comment]
so when you created the trainer you did /dc create <id> <name> <skill> 30 0  <entitytype>

**Comment by drekryan** [comment]
<img width="550" alt="screen shot 2018-02-25 at 1 14 46 am" src="https://user-images.githubusercontent.com/1168966/36638660-52cfdce8-19c9-11e8-9165-8f03c9a84614.png">

The trainer list should not be like this... This is what is looks like when incorrectly done. Min level should be 0 and max should be 30 if using the default levels.

**Comment by tylerking** [comment]
Hmm ok...there are both 0 0. See these trainers are the same trainers I made a looooong time ago because they were already skinned I kept them.

**Comment by drekryan** [comment]
I think you can manually fix it to 30 in the Citizens saves.yml file

**Comment by tylerking** [comment]
Yeah...I'm doing a find and replace right now. Should fix it.

**Comment by tylerking** [comment]
Yep. Fixed. Easy. Thank you.
