### ISSUE TITLE
Can't Pickup Drops

### ISSUE THREAD

**Issue by tylerking** [Jessy1237/DwarfCraft#74]
Hey. So with Dwarfcraft installed after crafting an item you can no longer pick up drops. I've already gone through all my other plugins and this only happens with Dwarfcraft. There are no errors in the console or anything. Just craft an item, drop it and then you can't pick it up.

**Comment by Jessy1237** [comment]
I'll begin looking into this tomorrow

**Comment by tylerking** [comment]
I had to shut down my server because of this one.

**Comment by Jessy1237** [comment]
does this occur in both inventory crafting and in the crafting table?

**Comment by Jessy1237** [comment]
well i've been able to replicate it. Odd that this is occurring as the crafting code hasn't been touched. I'll try looking for a fix

**Comment by Jessy1237** [comment]
what is even weirder is after the player relogs they can pickup items again.

**Comment by tylerking** [comment]
Yep. That's pretty much what the players were doing yesterday every time they crafted an item.

**Comment by Jessy1237** [comment]
well it seems the a line of code is missing. idk how longs its been missing for but i'll release a fix now after i've tested it.

**Comment by tylerking** [comment]
Perfect. Thanks for tending to this one so fast.

**Comment by Jessy1237** [comment]
I won't enough time to release a build on spigot however you can make a build form this source code if you know how to use maven.

**Comment by tylerking** [comment]
I do and I will. Thank you.

**Comment by drekryan** [comment]
This fix doesn't properly fix furnace shift-clicking after the first shift click.

ie. shift-clicking ingots out of the furnace once works fine the first time but any after the first causes this issue again. Its 90% fixed but going to reopen this issue.

**Comment by Jessy1237** [comment]
Sorry about that I was in a rush yesterday and didn't have enough time to test it fully. Both issues are now rectified as in e17086a as I have done an overhaul on the furnace handling and shift clicking code. I will release a build on spigot shortly
