### ISSUE TITLE
Error when doing /dc tutorial

### ISSUE THREAD

**Issue by jamesol1** [Jessy1237/DwarfCraft#75]
I'm using spigot 1.12.2 and the latest version of your plugin. I have all the plugin requirements, everything else seems to work but this.

02.03 05:34:10 [Server] ERROR null
02.03 05:34:10 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'dc' in plugin DwarfCraft v4.1.2
02.03 05:34:10 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot131.jar:git-Spigot-7754231-94b0980]
02.03 05:34:10 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot131.jar:git-Spigot-7754231-94b0980]
02.03 05:34:10 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:651) ~[spigot131.jar:git-Spigot-7754231-94b0980]
02.03 05:34:10 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1392) [spigot131.jar:git-Spigot-7754231-94b0980]
02.03 05:34:10 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1227) [spigot131.jar:git-Spigot-7754231-94b0980]
02.03 05:34:10 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot131.jar:git-Spigot-7754231-94b0980]
02.03 05:34:10 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot131.jar:git-Spigot-7754231-94b0980]
02.03 05:34:10 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot131.jar:git-Spigot-7754231-94b0980]
02.03 05:34:10 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_144]
02.03 05:34:10 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_144]
02.03 05:34:10 [Server] INFO at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot131.jar:git-Spigot-7754231-94b0980]
02.03 05:34:10 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot131.jar:git-Spigot-7754231-94b0980]
02.03 05:34:10 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot131.jar:git-Spigot-7754231-94b0980]
02.03 05:34:10 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot131.jar:git-Spigot-7754231-94b0980]
02.03 05:34:10 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot131.jar:git-Spigot-7754231-94b0980]
02.03 05:34:10 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
02.03 05:34:10 [Server] INFO Caused by: java.lang.NoSuchMethodError: org.bukkit.inventory.meta.BookMeta.spigot()Lorg/bukkit/inventory/meta/BookMeta$Spigot;
02.03 05:34:10 [Server] INFO at com.Jessy1237.DwarfCraft.commands.CommandTutorial.createTutorialBook(CommandTutorial.java:119) ~[?:?]
02.03 05:34:10 [Server] INFO at com.Jessy1237.DwarfCraft.commands.CommandTutorial.execute(CommandTutorial.java:55) ~[?:?]
02.03 05:34:10 [Server] INFO at com.Jessy1237.DwarfCraft.DwarfCraft.onCommand(DwarfCraft.java:290) ~[?:?]
02.03 05:34:10 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot131.jar:git-Spigot-7754231-94b0980]
02.03 05:34:10 [Server] INFO ... 15 more

**Comment by drekryan** [comment]
Your version of Spigot seems to be quite old. Please run /version in game and post that here

**Comment by drekryan** [comment]
Your version of Spigot is from Sept. 2017 which is about 6 months old now. We require December 2017 Spigot or later. However it is best to be running the latest version of Spigot by building it yourself with the Spigot BuildTools. Please reopen this issue if after updating Spigot you still run into this problem.
