### ISSUE TITLE
Changing prefix / using prefix with TownyChat

### ISSUE THREAD

**Issue by h0ldthemay0** [Jessy1237/DwarfCraft#77]
DwarfCraft 4.1.3 / spigot 1.12.2

Attempting to use dwarfcraft race prefixes with Towny. I would like to (ideally) not show the races' names, instead only changing the color name of the user.  Not sure if this is an already existing feature or not.

Also I am unable to even display the race name while using TownyChat to manage global chat. 
Pastebin of the error

https://pastebin.com/PbE93hum

**Comment by Jessy1237** [comment]
As far as i'm aware vault doesn't support townychat so the prefixes will only be applied to a chat plugin that vault supports. However to achieve the result you want you can have the prefix being blank under the races config and it should still apply the colour. Also with the pastebin error it seems to be a townychat issue not a dwarfcraft issue.
