### ISSUE TITLE
Disabling "Train and Deposit Skill" option

### ISSUE THREAD

**Issue by JesterOwl** [Jessy1237/DwarfCraft#78]
#### Issue type:

- :question: Question

____

#### Question:

Hello, I've been planning to use Dwarfcraft on a server that's coming out soon, but we have a sort of annoying issue with the "Train & Deposit" option for trainers. I was wondering if there is a way to disable specifically that option, because the seperate "Deposit" and "Train" buttons from trainers work perfectly as intended, however when use the combined "Train & Deposit" button it glitches and allows the players to take out all of the items in the Trainer GUI, so they get free Barriers, etc.

Thank you for any response, sorry if this should have been posted as an issue, I just placed it as a question since the server uses a ton of plugins and it might be hard to find what exactly is causing it, so

Is it possible to disable specifically the "Train and Deposit Skill" option???  (I can re-post this as an issue if you guys would like, with plugin list and a video if necessary)

**Comment by Jessy1237** [comment]
Are there any errors posted to the console during startup or when encountering this issue? Ok so i've been able to replicate it as you've said but also on the usual train option as well. I'll have a look for a fix.

**Comment by Jessy1237** [comment]
Give this version a go. It should fix this issue for you.

**Comment by JesterOwl** [comment]
Thank you! it seems to be fixed, I really appreciate it.
