### ISSUE TITLE
Adding commands after leveling up

### ISSUE THREAD

**Issue by JesterOwl** [Jessy1237/DwarfCraft#81]
#### Issue type:

- :heavy_plus_sign: Feature request

____

#### Short description:
I'd like to request a feature that allows for the configuration of commands to be played when a player levels up from a trainer. I'd love to be able to grant permission groups to players who get max level so they can get a prefix reward.

For example, when a player reaches level 30 on a mining skill, a command is run,
like "/pex user group add etcetc", or a command to give them a reward like a crate key or something.

Note: If it's difficult to add that in please don't worry about it-- it's not that important, especially since you guys are working to update to 1.13. I just thought it might be easy since there is already an option to send an announcement out every 5 levels, I thought it could be an easy addition.

**Comment by drekryan** [comment]
@JesterOwl 

Hey so I love this idea! I think it fits very well with ways I plan to use the plugin in the future as well and think it would be a good thing to add.

I started messing around with the code for fun and made some progress towards maybe getting this into the plugin.

Below is a screenshot of what I have changed the config file to so far (things may still change and I don't know if im expanding it to too many sets of commands yet, have to see how things go).

I have the config file being read into the plugin so far and the commands running. I just have some more refinements to make on it for example deciding under which conditions the commands are run under, supporting more placeholders, and chat colors (which are both easy to add in).

The only thing is an admin can adjust the level of a skill for a player to anything. So currently I think if an admin sets their skill I will only run the commands if their level increases from the previous level and run them the number of times they increased level.

If they were level 5 and an admin sets them to level 1, I feel thats a case we wouldn't run any commands. Or maybe when an admin sets a players level, level up commands are never run. Something ill have to think about.

Thanks for the idea! Glad to see you like the plugin.

![dclevelcommands](https://user-images.githubusercontent.com/1168966/42417595-50a77394-825c-11e8-8c95-62cc41d7e275.png)

**Comment by JesterOwl** [comment]
Yes, thanks again. The config looks perfect!

And yea, plugin is awesome, and so much more awesome that you guys are so active. I really appreciate it.

The plugin works really well in this sort of mmo-rpg server, where the players can focus on leveling the current trainers when they finish rpg content, which gives me a little more time to work on expansions with quests and stuff : ] 100% the most important plugin on the server.

**Comment by Jessy1237** [comment]
if you need this feature asap it should be fairly easy to whip up a companion plugin with the DwarfCraft API to do this if you know any java. As i have spotty internet reception for probably the next month...

**Comment by drekryan** [comment]
already in master

**Comment by drekryan** [comment]
it doesnt currently use the API methods which are in need of cleanup anyway
