### ISSUE TITLE
McMmo Incompatibility 

### ISSUE THREAD

**Issue by JesterOwl** [Jessy1237/DwarfCraft#83]
#### Issue type:

- :bug: Bug

____

#### Short description:

McMmo currently does not give experience from any item affected by dwarfcraft. Removing dwarfcraft fixes the issue, and I was wondering if it would be possible to fix this as we have several plugins that affect items in different ways, and they seem to work with mcmmo.

#### Steps to reproduce the problem:

(On a fresh test server with only plugins-- Dwarfcraft, PermissionsEx, Vault, Citizens, and McMmo)
1. Try to mine stone: Stone, Iron, and Coal does not give mining experience 
(For easy testing, doing the command /mining, opens up a scoreboard showing exp gain)
2. Wood does not give experience for Woodcutting
3. There are a lot of items, and mostly just the ones affected by Dwarfcraft don't give Experience to McMmo level trees.
#### Expected behavior:

Normally, mining resources, like stone, give experience to the McMmo Mining tree. 

#### Does this issue happen on vanilla DwarfCraft without plugins?
_(place X in box to check)_
- [ ] No
- [X] Yes (A fresh install of Dwarfcraft, It's requirements, and McMmo.)

#### Please list all plugins installed on your server
_Vault, Citizens, Permissions Ex, Dwarfcraft, McMmo

#### Other Notes

Some skills from McMmo, like Tree Feller ( a skill that chops the entire tree down from breaking one block) does not work either.
#### Versions:

- DwarfCraft: 4.1.3
- Minecraft: 1.12.2
- Spigot: spigot-1.12.2_6_20.jar
- McMmo: https://www.spigotmc.org/resources/mcmmo.2445/
Note: The Mcmmo devs provide a free download for all their builds as well, which is linked in their spigot but also here: https://popicraft.net/jenkins/job/mcMMO/

#### Log file:

Breaking blocks and experience aren't shown in the logs so they might be useless, but here:

https://pastebin.com/zXPadBhG

**Comment by drekryan** [comment]
Fixed as of DwarfCraft 4.1.6
