### ISSUE TITLE
Command Permissions not working

### ISSUE THREAD

**Issue by Nahubi** [Jessy1237/DwarfCraft#87]
#### Issue type:

- :bug: Bug Report

____

#### Short description:

Says I don't have permission to use command (while op/or not) for any of the commands

#### Steps to reproduce the problem:

I don't know. I just installed it and it happened.

____

#### Versions:

- DwarfCraft: latest
- Minecraft: 1.13.2
- Spigot: 1.13.2

**Comment by drekryan** [comment]
Which version of Vault are you using and which permissions plugin are you using? PEX, luckyPerms? And the version of your permissions plugin.

**Comment by Nahubi** [comment]
Vault I do think is latest?
Permissions is bPermissions-2.12

**Comment by drekryan** [comment]
There are some issues with the permission nodes which I will fix up in the next release.

OP permissions should allow you to bypass the permission nodes but aren't working the way they should.
Not all permission nodes are working for individual commands with is another issue that will need to be addressed.

I recommend for now to give yourself all permissions if you have op permissions.

- /user [ign]
- /user addperm dwarfcraft.*

That should force DwarfCraft to allow you to run all commands.

**Comment by Nahubi** [comment]
Thank you! that worked. Thanks for the hard work as well!

**Comment by drekryan** [comment]
@Nahubi you’re welcome! Thanks for supporting the plugin. Please make us aware of any other issues you may have. 

While we are focused on 1.14 for new features and getting that release finished we are still supporting the 1.13 release with bug fixes.

**Comment by drekryan** [comment]
@Nahubi I found and fixed some DwarfCraft issues for Minecraft 1.13 and put a version of the fixes here on github before a Spigot release.

Would you be interested in testing them out for me since you seem to be on Minecraft 1.13.2?

The release notes explain the changes and bugs fixed.
Release is here: https://github.com/Jessy1237/DwarfCraft/releases/tag/4.2.2
