### ISSUE TITLE
Trainers removed after update

### ISSUE THREAD

**Issue by tylerking** [Jessy1237/DwarfCraft#9]
The latest update removed all of my trainers. Of course all of the Citizen NPCs are still there but they are no longer Trainer NPCs. I had all of them positioned and setup perfectly and the thought of having to go back and delete all 54 NPCs and recreate those trainers is kind of a drag. Can you create a command to assign the trainer traits to already existing Citizens NPCs please?

**Comment by Jessy1237** [comment]
So does it remove the trainer trait on every server restart?

**Comment by tylerking** [comment]
Good news. I actually didn't even try to restart the server again but I did and noticed they were back so I tried the /dcreload command and they are only disappearing when you run that command. So its not nearly as bad as I thought it was.

**Comment by Jessy1237** [comment]
Ahhhh I believe I know what's doing it, should be a simple fix.
