### ISSUE TITLE
Lacking permissions even in console

### ISSUE THREAD

**Issue by SauROnmiKE** [Jessy1237/DwarfCraft#90]
#### Issue type:

- :bug: Bug

____

#### Short Description:
I can't run any command of DwarfCraft, even from the console due to lack of permissions. No permissions plugin installed yet.

#### Steps to reproduce the problem:
1. Ran server
2. Executed any DwarfCraft command

#### Expected behaviour:
Should execute commands

#### Does this issue happen on DwarfCraft without other plugins?

_(place X in box to check)_
[ ] No
[X ] Yes

#### Please list ALL plugins installed on your server:
_Vault, Citizens, Boss, DungeonsXL, Essentials, Factions, LoginSecurity, mcMMOHorse, MMOItems, MMOLib, MythicMobs, UltimateModeration, UberEnchant, WorldEdit, WorldGuard

#### Versions:

- DwarfCraft: 4.2.2
- Minecraft: 1.12.2
- MAGMA with PaperSpigot #1618

**Comment by drekryan** [comment]
A Vault compatible permissions plugin is a requirement of DwarfCraft.

Some commands (such as skillsheet and skillinfo commands) the way they are formatted are not intended to be displayed in the console but can be run as an admin in game.

All admin commands such as changing skill levels and race can be run from the console with a permissions plugin.
